## UFSM00041 - MATEMÁTICA COMPUTACIONAL II
### Atividade Avaliativa #1
#### Prof. Tiago Buriol   - 1º Semestre de 2024

### Nome do aluno:


**Atividade:** Use as funções Pyhton e Numpy estudadas em aula para escrever vetores e matrizes como `arrays` e realizar o que se pede a seguir.

Dadas as matrizes
$A= \left[\begin{array}{ccc}
	         1 & 2  & 3 \\
	         -1 & 5 &  0 \\
	         7 & -2 &  4 \\
	         \end{array} \right]$,
$M= \left[\begin{array}{ccc}
	         4.230 & 5.110 & 7.430 \\
	         -6.555 &  1.895 & 10.855  \\
	         10.010 & 5.550 & 2.670 \\
	         \end{array} \right]$ e
$N=\left[\begin{array}{cccc}\frac{1}{2} & \frac{-1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{-1}{2} \\ \frac{-1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & \frac{-1}{2} & \frac{1}{2}\end{array}\right]$
e o vetor $b = \left[
            \begin{array}{c}
	          3 \\
	         -1  \\
	          0 \\
	         \end{array} \right]$,

**1.** Calcule o módulo (ou magnitude) do vetor $b$. Em seguida obtenha um vetor unitário $\hat{b}$ na direção de $b$ e verifique que $\sqrt{\langle \hat{b}, \hat{b}\rangle }=1$.

In [1]:
import numpy as np

In [12]:
A = np.array([[1, 2, 3],[-1, 5, 0],[7, -2, 4]])
M = np.array([[4.230, 5.110, 7.430], [-6.555, 1.895, 10.855], [10.010, 5.550, 2.670]])
N = np.array([[0.5,-0.5,0.5,0.5], [0.5,0.5,0.5,-0.5], [-0.5,0.5,0.5,0.5], [0.5,0.5,-0.5,0.5]])
b = np.array([3, -1, 0])
print(A)
print(M)
print(N)
print(b)

[[ 1  2  3]
 [-1  5  0]
 [ 7 -2  4]]
[[ 4.23   5.11   7.43 ]
 [-6.555  1.895 10.855]
 [10.01   5.55   2.67 ]]
[[ 0.5 -0.5  0.5  0.5]
 [ 0.5  0.5  0.5 -0.5]
 [-0.5  0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]]
[ 3 -1  0]


In [13]:
#1)magnitude
mag_b = np.sqrt(np.dot(b,b))
print(mag_b)

3.1622776601683795


In [19]:
#1)vetor unitario e verificação
b_unit = b / mag_b
print(v_unit)

mag_b_unit = np.round(np.sqrt(np.dot(b_unit, b_unit)))
print(mag_b_unit)

[ 0.9486833  -0.31622777  0.        ]
1.0


**2.** Verifique que a segunda linha ($L_2$) da matriz $M$ é a combinação linear  $L_2 = 2L_1- \frac{3}{2}L_3$ da primeira ($L_1$) e da terceira ($L_3$) linhas. Então, calcule o determinante. Essa matriz é invertível?

In [20]:
#2)Verificação
2*M[0,:]-3/2*M[2,:]

array([-6.555,  1.895, 10.855])

In [21]:
#2)Determinante e se é invertível
M = np.array([[4.230, 5.110, 7.430], [-6.555, 1.895, 10.855], [10.010, 5.550, 2.670]])
np.linalg.det(M)


0.0

In [ ]:
#Como o determinante da matriz é zero, essa matriz não possui inversa.

**3.** Verifique que o produto vetorial $u_1 \times u_2$ de dois vetores dados por duas linhas quaisquer de $A$ resulta em um vetor ortogonal a $u_1$ e também a $u_2$.

In [35]:
#3)Vetores 1 e 2 referentes a linha 1 e 2 de A
u1 = np.array(A[0])
u2 = np.array(A[1])
print(u1)
print(u2)

[1 2 3]
[-1  5  0]


In [38]:
#Produto vetorial
u12 = np.cross(u1, u2)
print(u12)

[-15  -3   7]


In [39]:
#calculo dos produtos escalares
np.dot(u12, u1)

0

In [40]:
np.dot(u12, u2)

0

In [ ]:
#Portanto prova-se que ambos são ortogonais

**4.** Calcule o determinante das matrizes $A$, $M$ e $N$. Qual dessas 3 matrizes possuem inversa?

In [22]:
#4)
A = np.array([[1, 2, 3],[-1, 5, 0],[7, -2, 4]])
np.linalg.det(A)

-71.0

In [23]:
#4)
M = np.array([[4.230, 5.110, 7.430], [-6.555, 1.895, 10.855], [10.010, 5.550, 2.670]])
np.linalg.det(M)

0.0

In [24]:
#4)
N = np.array([[0.5,-0.5,0.5,0.5], [0.5,0.5,0.5,-0.5], [-0.5,0.5,0.5,0.5], [0.5,0.5,-0.5,0.5]])
np.linalg.det(N)

1.0

In [ ]:
#As matrizes que possuem inversa são: A e N, pois suas determinantes são diferente de 0.

**5.** Extraia uma matriz triangular superior da matriz $A$ e verifique que o determinante da matriz triangular é igual ao produto dos elementos de sua diagonal principal.

In [31]:
#5)
A = np.array([[1, 2, 3],[-1, 5, 0],[7, -2, 4]])
print(A)

[[ 1  2  3]
 [-1  5  0]
 [ 7 -2  4]]


In [27]:
tri_A = np.tril(A)

array([[ 1,  0,  0],
       [-1,  5,  0],
       [ 7, -2,  4]])

In [30]:
tri_A = np.array([[1, 0, 0],[-1, 5, 0],[7, -2, 4]])
np.linalg.det(tri_A)

19.999999999999996

In [32]:
d = np.diag(A)
print(d)

[1 5 4]


In [33]:
1*5*4

20

In [ ]:
#Verificamos que o determinante da matriz triangular superior é praticamente o mesmo valor da diagonal principal.

**6.** Obtenha a inversa de $A$ e use-a para obter o vetor $x$ tal que $x = A^{-1}b$. Então, verifique que $x$ é a solução do sistema $Ax=b$, calculando o produto $Ax$ e comparando com o vetor $b$.

In [34]:
#6)
Ainv = np.linalg.inv(A)
print(Ainv)

[[-0.28169014  0.1971831   0.21126761]
 [-0.05633803  0.23943662  0.04225352]
 [ 0.46478873 -0.22535211 -0.09859155]]


In [59]:
x = np.round(Ainv@b)
print(x)

[-1. -0.  2.]


In [61]:
x = np.array([[-1, -0, 2]])
x@A

array([[13, -6,  5]])

**7.** Verifique que $N$ é uma matriz ortogonal mostrando que $N^{-1}=N^T$. Então, tome dois vetores, $u_1$ e $u_2$, dados por duas colunas quaisquer de $N$ e verifique que são ortogonais entre si, ou seja, $\langle u_1, u_2\rangle =0$.

**8.** O método de ortogonalização de Gram-Schmidt consiste em um algoritmo que permite obter um conjunto de vetores ortogonais entre si a partir de um conjunto linearmente independentes de outros vetores. Para um conjunto de três vetores $\{ v_1, v_2, v_3\}$ o processo pode ser descrito por
$$
\begin{aligned}
& u_1=v_1 \\
& u_2=v_2-\frac{\left\langle v_2, u_1\right\rangle}{\left\langle u_1, u_1\right\rangle} u_1 \\
& u_3=v_3-\frac{\left\langle v_3, u_1\right\rangle}{\left\langle u_1, u_1\right\rangle} u_1-\frac{\left\langle v_3, u_2\right\rangle}{\left\langle u_2, u_2\right\rangle} u_2
\end{aligned}
$$

Obtenha os vetores ortogonais $u_1$, $u_2$ e $u_3$ e verifique que o produto interno entre um par qualquer é zero.

**9.**  O parábola que passa pelos pontos $(2,-2)$, $(3,-5)$ e $(4,0)$ pode ser obtida resolvendo o sistema linear

$$ y_i = ax_i^2 + bx_i+c $$

com $(x_i, y_i)$, $i = 1,2,3$ sendo os pontos dados acima. A matriz dos coeficientes do sistema resultante é conhecida como Matriz de Vandermonde. Escreva o sistema na forma matricial e resolva usando matriz inversa ontendo os coeficientes $a$, $b$ e $c$. Então plote o gráfico do parábola e dos pontos.

**10.** Em muitas aplicações é necessário encontrar uma função que representa um conjunto de dados obtidos usando uma aproximação por minimos quadradados.

Podemos encontrar o polinômio de grau 3 que melhor representa um conjunto de 10 pontos $(x_i, y_i)$, $i=1,2,...,10$, por mínimos quadrados, resolvendo o sistema linear

$$(Z^TZ)a = Z^Ty$$

onde $Z$ é a matriz $10\times4$ obtida a partir dos valores de $x_i$, $i=1,2,...,10$ fazendo

$$Z = \left[\begin{matrix}
1 & x_1 & x_1^2 & x_1^3\\
1 & x_2 & x_2^2 & x_2^3\\
1 & x_3 & x_3^2 & x_3^3\\
\vdots & \vdots & \vdots & \vdots\\
1 & x_{10} & x_{10}^2 & x_{10}^3\\
\end{matrix}\right]$$

$a$ é a matriz dos coeficientes do polinômio $a=[a_0, a_1, a_2,a_3]^T$ e $y$ é dado por $y=[y_1,y_2,...,y_{10}]^T$.

Monte e resolva o sistema para encontrar o polinômio, então, plote o gráfico desse polinômio juntamente com os pontos:

x (m) |  1,3 |  0,9 |  2,2 | 1,95 | 1,78 | 3,1  | 2,48 | 2,74 | 3,35 | 3,99 |
------|------|------|------|------|------|------|------|------|------|------|
y (cm)|  1,9 | 3,01 | -3,1 | -1.98| -1.53| -5.01|-4.91 |-5.01 |-4.02 | 0,15 |