## UFSM00041 - MATEMÁTICA COMPUTACIONAL II - T10_315
### Atividade Avaliativa #1
#### Prof. Tiago Buriol
#### 2º Semestre de 2023

### Nome do aluno:


**Atividade:** Usar as funções de Pyhton e Numpy estudados em aula para descrever vetores e matrizes como `arrays` e realizar o que se pede a seguir.

Dadas as matrizes
$A= \left[\begin{array}{ccc} 
	         1 & 2  & 3 \\ 
	         -1 & 5 &  0 \\
	         7 & -2 &  4 \\
	         \end{array} \right]$,
$M= \left[\begin{array}{ccc} 
	         1 & 2  & 3 \\ 
	         11 & -2 & 7.5  \\
	         7 & -2 &  4 \\
	         \end{array} \right]$ e
            

$N=\frac 1{\sqrt{6}}\begin{pmatrix} \sqrt{2} & 1 & \sqrt{3} \\ -\sqrt{2} & 2 & 0 \\ \sqrt{2} & 1 & -\sqrt{3} \end{pmatrix}$


e o vetor $b = \left[ 
            \begin{array}{c} 
	          3 \\ 
	         -1  \\
	          0 \\
	         \end{array} \right]$, 

**1.** Calcule o módulo (ou magnitude) do vetor $b$. Em seguida obtenha um vetor unitário $\hat{b}$ na direção de $b$ e verifique que $\sqrt{\langle \hat{b}, \hat{b}\rangle }$.

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [85]:
A = np.array([[1, 2, 3], [-1, 5, 0], [7, -2, 4]])
M = np.array([[1, 2, 3], [11, -2, 7.5], [7, -2, 4]])
b = np.array([3,-1,0])

In [99]:
3**1/2+-1**1/2+0**1/2

1.0

In [112]:
b[1:]

array([-1,  0])

In [115]:
-1-1**1/2

-1.5

**2.** Verifique que a segunda linha ($L_2$) da matriz $M$ é a combinação linear  $L_2 = \frac{1}{2}L_1+\frac{3}{2}L_3$ da primeira ($L_1$) e da terceira ($L_3$) linhas.

In [5]:
1/2*M[0] + 3/2*M[2]

array([11. , -2. ,  7.5])

**3.** Verifique que dois vetores $u_1$ e $u_2$ dados por duas colunas quaisquer de $N$ são ortogonais entre si, ou seja, $\langle u_1, u_2\rangle =0$.

In [6]:
import numpy as np

N= (1/np.sqrt(6))*np.array([[np.sqrt(2),1,np.sqrt(3)],
                          [-np.sqrt(2),2,0],
                           [np.sqrt(2), 1,-np.sqrt(3)]])



In [104]:
N[0,0]*N[1,2]

0.0

**4.** Verifique que o produto vetorial de dois vetores $u_1$ e $u_2$ dados por duas colunas quaisquer de $N$ resulta em um vetor múltiplo da terceira coluna.

In [109]:
np.dot(N[:,0],N[:,1])

0.0

In [110]:
N[:,1]

array([0.40824829, 0.81649658, 0.40824829])

**5.** Calcule o determinante das matrizes $A$, $M$ e $N$. Qual dessas 3 matrizes possuem inversa?

In [7]:
np.linalg.det(A)

-71.0

In [8]:
np.linalg.det(M)
np.round(np.linalg.det(M))

-0.0

In [11]:
np.linalg.det(N)
np.round(np.linalg.det(N))

-1.0

In [13]:
Ainv = np.linalg.inv(A)
np.round(A@Ainv)

array([[ 1., -0., -0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
Minv = np.linalg.inv(M)
np.round(M@Minv)

array([[ 0.,  0., -1.],
       [ 0.,  0.,  0.],
       [-1.,  1.,  1.]])

In [16]:
Ninv = np.linalg.inv(N)
np.round(N@Ninv)

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

**6.** Obtenha a inversa de $A$ e use-a para obter o vetor $x$ tal que $x = A^{-1}b$. Então, verifique que $x$ é a solução do sistema $Ax=b$, calculando o produto $Ax$ e comparando com o vetor $b$. 

In [86]:
Ainv=np.linalg.inv(A)


In [94]:
Ainv.dot(b)

array([-1.04225352, -0.4084507 ,  1.61971831])

In [95]:
x=Ainv.dot(b)

In [98]:
np.round(A.dot(x))

array([ 3., -1.,  0.])

**7.** Verifique que $N$ é uma matriz ortogonal mostrando que $N^{-1}=N^T$.

In [72]:
Ninv=np.linalg.inv(N)
print(Ninv)


[[ 0.57735027 -0.57735027  0.57735027]
 [ 0.40824829  0.81649658  0.40824829]
 [ 0.70710678 -0.         -0.70710678]]


In [61]:
N.T

array([[ 0.57735027, -0.57735027,  0.57735027],
       [ 0.40824829,  0.81649658,  0.40824829],
       [ 0.70710678,  0.        , -0.70710678]])

**8.** Extraia uma matriz triangular superior da matriz $A$ e verifique que o determinante da matriz triangular é igual ao produto dos elementos de sua diagonal principal. 

In [19]:
A1 = np.array([[1, 2, 3], [-1, 5, 0], [7, -2, 4]])
print(A1)

[[ 1  2  3]
 [-1  5  0]
 [ 7 -2  4]]


In [20]:
np.triu(A1)

array([[1, 2, 3],
       [0, 5, 0],
       [0, 0, 4]])

In [21]:
np.linalg.det(np.triu(A1))

19.999999999999996

**9.**  Verifique que trocando duas linhas da matriz identidade e multiplicando por qualquer uma das matrizes dadas, o resultado obtido é a matriz com as mesmas linhas trocadas.

In [56]:
i = np.array([[1,0,0], [0, 0, 0], [0, 0, 0]])
print(i)

[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [58]:
i@A

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

**10.** Faça o escalonamento da matriz $A$ usando operações elementares sobre linhas  da matriz.

In [121]:
A[:0]+A[:1]

array([], shape=(0, 3), dtype=int64)