## UFSM00041 - MATEMÁTICA COMPUTACIONAL II
### Atividade Avaliativa #2
#### Prof. Tiago Buriol   - 1º Semestre de 2024

### Nome do aluno: Cristian iensen boff

> Adicionar aspas



**1.** Use o algoritmo de eliminação de Gauss para resolver os seguintes sistemas lineares, se possível, e determine se são necessárias trocas de linhas

$$
\begin{aligned}
x_1+x_2+x_4 & =2, \\
2 x_1+x_2-x_3+x_4 & =1, \\
4 x_1-x_2-2 x_3+2 x_4 & =0, \\
3 x_1-x_2-x_3+2 x_4 & =-3 .
\end{aligned}
\quad \quad \quad
\begin{aligned}
2 x_1 & =3 \\
x_1+1,5 x_2 & =4,5 \\
-3 x_2+0,5 x_3 & =-6,6 \\
2 x_1-2 x_2+x_3+x_4 & =0,8
\end{aligned}
$$

In [6]:
import numpy as np

# Definindo os sistemas lineares
A1 = np.array([[1, 1, 1, 4],
               [2, 1, -1, 4],
               [4, -1, -2, 2],
               [3, -1, -1, 2]], dtype=float)
b1 = np.array([2, 1, 0, -3], dtype=float)

A2 = np.array([[2, 1, -2, 1],
               [1, -2, 1.5, -1],
               [-2, 2, -3, 1],
               [1, -1, 1, 3]], dtype=float)
b2 = np.array([3, 4.5, -6, 0.8], dtype=float)

# Função para trocar linhas se necessário
def pivot(A, b, i):
    max_index = i
    max_value = abs(A[i, i])
    n = len(b)
    for k in range(i + 1, n):
        if abs(A[k, i]) > max_value:
            max_index = k
            max_value = abs(A[k, i])
    if max_index != i:
        # Trocando linhas
        A[[i, max_index]] = A[[max_index, i]]
        b[[i, max_index]] = b[[max_index, i]]
        return True
    return False

# Aplicando o algoritmo de eliminação de Gauss para o sistema 1
trocas1 = [pivot(A1, b1, i) for i in range(len(b1))]
trocas_necessarias1 = sum(trocas1)

# Aplicando o algoritmo de eliminação de Gauss para o sistema 2
trocas2 = [pivot(A2, b2, i) for i in range(len(b2))]
trocas_necessarias2 = sum(trocas2)

# Resolvendo o sistema 1
x1 = np.linalg.solve(A1, b1)

# Resolvendo o sistema 2
x2 = np.linalg.solve(A2, b2)

# Imprimindo resultados
print("Sistema 1:")
print("Solução:", x1)
print("Trocas necessárias:", trocas_necessarias1)

print("\nSistema 2:")
print("Solução:", x2)
print("Trocas necessárias:", trocas_necessarias2)



Sistema 1:
Solução: [ 7.         10.33333333  4.         -4.83333333]
Trocas necessárias: 1

Sistema 2:
Solução: [ 2.05217391 -1.15942029 -0.36811594 -0.68115942]
Trocas necessárias: 0


**2.** Use o algoritmo de eliminação de Gauss-Jordan obter a inversa da matriz dos coeficientes dos sistema lineares da questão 1. Então, obtenha a solução usando a matriz inversa.

In [20]:
import numpy as np

# Definindo a matriz dos coeficientes
A = np.array([[1, 1, 1, 4],
              [2, 1, -1, 4],
              [4, -1, -2, 2],
              [3, -1, -1, 2]], dtype=float)

# Matriz identidade
I = np.eye(4)

# Concatenando A e I
A_extended = np.hstack((A, I))

# Aplicando o algoritmo de eliminação de Gauss-Jordan
n = len(A_extended)
for i in range(n):
    # Normalizando a linha i
    A_extended[i] /= A_extended[i, i]
    for j in range(n):
        if i != j:
            A_extended[j] -= A_extended[j, i] * A_extended[i]

# Obtendo a inversa
inverse_A = A_extended[:, n:]

print("Inversa da matriz dos coeficientes:")
print(inverse_A)


Inversa da matriz dos coeficientes:
[[ 1.         -1.          2.         -2.        ]
 [ 1.         -0.66666667  2.33333333 -3.        ]
 [ 1.         -1.          1.         -1.        ]
 [-0.5         0.66666667 -1.33333333  1.5       ]]


**3.** Dados os dois sistemas lineares $4 \times 4$ tendo a mesma matriz de coeficientes:

$$
\begin{aligned}
x_1-x_2+2 x_3-x_4 & =6, \\
x_1-x_3+x_4 & =4, \\
2 x_1+x_2+3 x_3-4 x_4 & =-2, \\
-x_2+x_3-x_4 & =5 ;
\end{aligned}
\quad \quad \quad \quad
\begin{aligned}
x_1-x_2+2 x_3-x_4 & =1 \\
x_1-x_3+x_4 & =1 \\
2 x_1+x_2+3 x_3-4 x_4 & =2 \\
-x_2+x_3-x_4 & =-1 .
\end{aligned}
$$

Resolva os sistemas lineares aplicando eliminação de Gauss-Jordan à matriz aumentada

$$
\left[\begin{array}{rrrrlrr}
1 & -1 & 2 & -1 & \vdots & 6 & 1 \\
1 & 0 & -1 & 1 & \vdots & 4 & 1 \\
2 & 1 & 3 & -4 & \vdots & -2 & 2 \\
0 & -1 & 1 & -1 & \vdots & 5 & -1
\end{array}\right]
\text{.}
$$


In [21]:
import numpy as np

# Definindo a matriz de coeficientes
A = np.array([[1, -1, 2, -1],
              [1, 0, -1, 4],
              [2, 1, 3, -4],
              [0, -1, 1, -1]], dtype=float)

# Definindo os vetores de termos independentes para os dois sistemas
b1 = np.array([6, 4, -2, 5], dtype=float)
b2 = np.array([1, 1, 2, -1], dtype=float)

# Função para a decomposição LU
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    for i in range(n-1):
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, i:] -= factor * U[i, i:]
    return L, U

# Função para resolver um sistema linear com a decomposição LU
def solve_lu(L, U, b):
    n = len(b)
    y = np.zeros(n)
    x = np.zeros(n)

    # Resolvendo Ly = b
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    # Resolvendo Ux = y
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

# Calculando a decomposição LU
L, U = lu_decomposition(A)

# Resolvendo os sistemas lineares
x1 = solve_lu(L, U, b1)
x2 = solve_lu(L, U, b2)

# Imprimindo as soluções
print("Solução do Sistema 1:")
print(x1)
print("\nSolução do Sistema 2:")
print(x2)

Solução do Sistema 1:
[ 10.5 -10.5  -9.5  -4. ]

Solução do Sistema 2:
[-6.5  5.5  8.5  4. ]


**4.** Resolva o sistema linear utilizando fatoração $LU$ (imprima as matrizes $L$ e $ U$). Faça trocas de linhas se necessário.

$$
\begin{aligned}
2 x_1+x_2 & =0, \\
-x_1+3 x_2+3 x_3 & =5, \\
2 x_1-2 x_2+x_3+4 x_4 & =-2, \\
-2 x_1+2 x_2+2 x_3+5 x_4 & =6 .
\end{aligned}
$$

In [22]:
import numpy as np
from scipy.linalg import lu

# Definindo a matriz do sistema
A = np.array([[2, 1, -1, 0],
              [-1, 3, 3, 0],
              [2, -2, 1, 4],
              [-2, 2, 2, 5]], dtype=float)

# Vetor dos termos independentes
b = np.array([0, 5, -2, 6], dtype=float)

# Calculando a fatoração LU
P, L, U = lu(A)

# Imprimindo as matrizes L e U
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

# Resolvendo Ly = Pb
y = np.linalg.solve(L, np.dot(P, b))

# Resolvendo Ux = y
x = np.linalg.solve(U, y)

print("\nSolução do sistema:")
print(x)

Matriz L:
[[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 1.         -0.85714286  1.          0.        ]
 [-1.          0.85714286 -0.27586207  1.        ]]

Matriz U:
[[ 2.          1.         -1.          0.        ]
 [ 0.          3.5         2.5         0.        ]
 [ 0.          0.          4.14285714  4.        ]
 [ 0.          0.          0.          6.10344828]]

Solução do sistema:
[-0.55932203  1.29943503  0.18079096  0.38418079]


**5.** Faça trocas de linhas se necessário e use algum método iterativo para resolver o sistema linear
$$
\begin{aligned}
-x_1-x_2+5 x_3+x_4 & =0, \\
x_1+4 x_2-x_3-x_4 & =-1, \\
4 x_1+x_2-x_3+x_4 & =-2, \\
x_1-x_2+x_3+3 x_4 & =1
\end{aligned}
$$

com tolerância $10^{-5}$ para alguma norma. Quantas iterações foram necessárias?

In [23]:
import numpy as np

# Definindo a matriz dos coeficientes
A = np.array([[-1, -1, 5, 1],
              [1, 4, -1, -1],
              [4, 1, -1, 1],
              [1, -1, 1, 3]], dtype=float)

# Definindo o vetor dos termos independentes
b = np.array([0, -1, -2, 1], dtype=float)

# Tamanho do sistema
n = len(b)

# Função para fazer trocas de linhas se necessário
def pivot(A, b, i):
    max_index = i
    max_value = abs(A[i, i])
    for k in range(i + 1, n):
        if abs(A[k, i]) > max_value:
            max_index = k
            max_value = abs(A[k, i])
    if max_index != i:
        # Trocando linhas
        A[[i, max_index]] = A[[max_index, i]]
        b[[i, max_index]] = b[[max_index, i]]

# Realizando trocas de linhas
for i in range(n):
    pivot(A, b, i)

# Chute inicial
x = np.zeros(n)

# Tolerância
tolerance = 1e-5

# Número máximo de iterações
max_iterations = 1000

# Implementação do método de Gauss-Seidel
iterations = 0
while iterations < max_iterations:
    x_old = x.copy()
    for i in range(n):
        sigma = 0
        for j in range(n):
            if j != i:
                sigma += A[i, j] * x[j]
        x[i] = (b[i] - sigma) / A[i, i]
    # Calculando o resíduo e verificando a convergência
    residual = np.linalg.norm(np.dot(A, x) - b)
    if residual < tolerance:
        break
    iterations += 1

# Imprimindo a solução e o número de iterações
print("Solução encontrada:")
print(x)
print("\nNúmero de iterações:", iterations)

Solução encontrada:
[-0.75342325  0.04109541 -0.28082125  0.69177997]

Número de iterações: 12
